apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: c1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c1 
  name: c1
spec:
  port:
    targetPort:  
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: c1
    weight: 100 

