apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c1 
  name: c1
spec:
  ports:
  - port:  
    targetPort:  
  selector:
    app.kubernetes.io/instance: c1 

